kind: Service
apiVersion: v1
metadata:
   name: train
spec:
   type: NodePort
   selector:
     app: train
   ports:
     - port: 8080
       nodePort: 8080
     
---
     
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train
  labels:
    app: train
spec:
  replicas: 5
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: train-signal
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
